const fs = require('fs');
const path = require('path');

const BASE_URL = 'https://buywithkeep.com';

// Load slug lists generated by other build scripts
const communitySlugPath = path.join(__dirname, '../data/community-slugs.json');
const articleSlugPath = path.join(__dirname, '../data/article-slugs.json');

const communityslugs = fs.existsSync(communitySlugPath)
  ? JSON.parse(fs.readFileSync(communitySlugPath, 'utf8'))
  : [];

const articleSlugs = fs.existsSync(articleSlugPath)
  ? JSON.parse(fs.readFileSync(articleSlugPath, 'utf8'))
  : [];

// Build sitemap entries
const staticPages = [
  { loc: '/', priority: '1.0', changefreq: 'monthly' },
  { loc: '/faq/', priority: '0.8', changefreq: 'monthly' },
  { loc: '/articles/', priority: '0.7', changefreq: 'weekly' },
];

const communityPages = communityslugs.map(slug => ({
  loc: `/communities/${slug}/`,
  priority: '0.9',
  changefreq: 'monthly'
}));

const articlePages = articleSlugs.map(slug => ({
  loc: `/articles/${slug}/`,
  priority: '0.7',
  changefreq: 'monthly'
}));

const allPages = [...staticPages, ...communityPages, ...articlePages];

const today = new Date().toISOString().split('T')[0];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${allPages.map(p => `  <url>
    <loc>${BASE_URL}${p.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')}
</urlset>`;

fs.writeFileSync(path.join(__dirname, '../sitemap.xml'), xml, 'utf8');
console.log(`Sitemap updated: ${allPages.length} URLs (${communityPages.length} communities, ${articlePages.length} articles).`);
